site_name: Domino Container
site_description: HCL Domino community container image
repo_url: https://github.com/SmartCloud-y/domino-container/tree/develop

theme:
  name: material
  logo: assets/domino.svg
  favicon: favicon.ico
  features:
    - navigation.tabs
    #- navigation.instant
    - navigation.sections
    #- navigation.expand
    #- toc.integrate
    - toc.follow
  palette: 
    primary: white

markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra:
  generator: false