site_name: Domino Container
site_description: HCL Domino community container image
repo_url: https://github.com/SmartCloud-y/domino-container/tree/develop

theme:
  name: material
  logo: assets/domino.svg
  favicon: favicon.ico
  features:
    - navigation.tabs
    #- navigation.instant
    - navigation.sections
    #- navigation.expand
    - toc.integrate
    - toc.follow
  palette: 
    primary: white

markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - awesome-pages
  - build_plantuml:
      render: 'server' # or "local" for local rendering
      bin_path: '/usr/local/bin/plantuml' # ignored when render: server
      server: 'http://www.plantuml.com/plantuml' # offical plantuml server
      disable_ssl_certificate_validation: true # for self-signed and invalid certs
      output_format: 'svg' # or "png"
      diagram_root: 'docs/plantuml' # should reside under docs_dir
      output_folder: 'out'
      input_folder: 'src'
      input_extensions: '' # comma separated list of extensions to parse, by default every file is parsed

extra:
  generator: false